version: 2

defaults: &defaults
  working_directory: ~/marie-tour-bretagne
  docker:
    - image: node:11

jobs:
  marie_tour_bretagne:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Global
          command: yarn global add typescript
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build

      - deploy:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy -P $PROJECT_ID --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - marie_tour_bretagne:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master

